Fixed d78 update to run new code, from an updated d78. Moved git attributes file

diff --git a/bin/d78 b/bin/d78
--- a/bin/d78
+++ b/bin/d78
@@ -93,8 +93,9 @@ _install_devtools)
   fi
 ;;
 _update)
-git -C $BASE_DIR pull -q
-[ $? != 0 ] && echo "Update failed" && exit 1
+exec bash -c "git -C $BASE_DIR pull -q; [ \$? != 0 ] && echo 'Update failed' && exit 1; $0 post_update"
+;;
+_post_update)
 if [[ "$(git -C $BASE_DIR remote get-url origin)" != *78cap/d78.git ]]; then
   git -C $BASE_DIR remote set-url origin https://github.com/78cap/d78.git
   git -C $BASE_DIR branch -m master main
